'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categoria
    Public Property idCategoria As Integer
    Public Property nombreCategoria As String

    Public Overridable Property Producto As ICollection(Of Producto) = New HashSet(Of Producto)

End Class
