'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property idProducto As Integer
    Public Property codigo As String
    Public Property idCategoria As Integer
    Public Property descripcion As String
    Public Property precio As Double
    Public Property stock As Integer

    Public Overridable Property Categoria As Categoria
    Public Overridable Property Salida As ICollection(Of Salida) = New HashSet(Of Salida)

End Class
