'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class RegistrosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RegistrosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categoria() As DbSet(Of Categoria)
    Public Overridable Property Producto() As DbSet(Of Producto)
    Public Overridable Property Salida() As DbSet(Of Salida)
    Public Overridable Property p_Producto() As DbSet(Of p_Producto)
    Public Overridable Property Historial() As DbSet(Of Historial)
    Public Overridable Property hv() As DbSet(Of hv)
    Public Overridable Property vs_salida() As DbSet(Of vs_salida)

    Public Overridable Function sp_insertProducto(codigo As String, idCategoria As Nullable(Of Integer), nombreCategoria As String, descripcion As String, precio As Nullable(Of Double), stock As Nullable(Of Integer)) As Integer
        Dim codigoParameter As ObjectParameter = If(codigo IsNot Nothing, New ObjectParameter("codigo", codigo), New ObjectParameter("codigo", GetType(String)))

        Dim idCategoriaParameter As ObjectParameter = If(idCategoria.HasValue, New ObjectParameter("idCategoria", idCategoria), New ObjectParameter("idCategoria", GetType(Integer)))

        Dim nombreCategoriaParameter As ObjectParameter = If(nombreCategoria IsNot Nothing, New ObjectParameter("nombreCategoria", nombreCategoria), New ObjectParameter("nombreCategoria", GetType(String)))

        Dim descripcionParameter As ObjectParameter = If(descripcion IsNot Nothing, New ObjectParameter("descripcion", descripcion), New ObjectParameter("descripcion", GetType(String)))

        Dim precioParameter As ObjectParameter = If(precio.HasValue, New ObjectParameter("precio", precio), New ObjectParameter("precio", GetType(Double)))

        Dim stockParameter As ObjectParameter = If(stock.HasValue, New ObjectParameter("stock", stock), New ObjectParameter("stock", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_insertProducto", codigoParameter, idCategoriaParameter, nombreCategoriaParameter, descripcionParameter, precioParameter, stockParameter)
    End Function

    Public Overridable Function sp_salidas(idSalida As Nullable(Of Integer), fechaSalida As Nullable(Of Date), idProducto As Nullable(Of Integer), cantidadSalida As Nullable(Of Integer)) As ObjectResult(Of sp_salidas_Result)
        Dim idSalidaParameter As ObjectParameter = If(idSalida.HasValue, New ObjectParameter("idSalida", idSalida), New ObjectParameter("idSalida", GetType(Integer)))

        Dim fechaSalidaParameter As ObjectParameter = If(fechaSalida.HasValue, New ObjectParameter("fechaSalida", fechaSalida), New ObjectParameter("fechaSalida", GetType(Date)))

        Dim idProductoParameter As ObjectParameter = If(idProducto.HasValue, New ObjectParameter("idProducto", idProducto), New ObjectParameter("idProducto", GetType(Integer)))

        Dim cantidadSalidaParameter As ObjectParameter = If(cantidadSalida.HasValue, New ObjectParameter("cantidadSalida", cantidadSalida), New ObjectParameter("cantidadSalida", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_salidas_Result)("sp_salidas", idSalidaParameter, fechaSalidaParameter, idProductoParameter, cantidadSalidaParameter)
    End Function

End Class
