'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Salida
    Public Property idSalida As Integer
    Public Property fechaSalida As Date
    Public Property idProducto As Integer
    Public Property cantidadSalida As Integer

    Public Overridable Property Producto As Producto

End Class
